### ISSUE TITLE
Add github references

### ISSUE THREAD

**Issue by haxwell** [haxwell/quizki#192]
People should be able to get to this github repo easily from Quizki.

**Comment by haxwell** [comment]
TODO: Add a circular, Github logo to the bottom of the home page. When you click on it, it should take you to the main page: http://github.com/haxwell/quizki.

**Comment by haxwell** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [#192 - Add Github references](https://trello.com/c/nAGJF52Z/2-192-add-github-references)

**Comment by jdisser** [comment]
Created a pull request for this issue just now. The request both addresses the logo issue and removes the project related files from the repo along with modification to the .gitignore file to stop tracking them. Not sure if this will work correctly since the files are in the index of Haxwell master.

In the process of setting up and getting familiar with Eclipse I must have changed the file mentioned in the pull request. Attempting to remove the changes using git on my local copy failed and they wound up in this branch. I added another commit to reverse them using the comparison to master in the pull request. The output from that and an explanation of how the file was restored is listed below

**Comment by jeremiah-shore** [comment]
thanks for updating the .gitignore for eclipse, I'm going to open a new issue for IntelliJ for that same reason, to do later when I'm not in the middle of other changes

**Comment by haxwell** [comment]
Addressed with PR #201
